version: 0.2
phases:
  install:
    commands:
      - ls -lah
      - curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
      - sudo bash nodesource_setup.sh
      - sudo apt install nodejs
      - sudo npm install -g aws-cdk
      - mv $CODEBUILD_SRC_DIR_BuildArtifact/deploy ./
      - ls -lah
  build:
    commands:
      - ./deploy.sh
