version: 0.2
phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
      - sudo bash nodesource_setup.sh
      - sudo apt install nodejs
      - node -v
  build:
    commands:
      - ./deploy.sh
