version: 0.2
phases:
  install:
    commands:
      - apt-get update -y
      - sudo apt-get install -y dotnet-sdk-6.0
      - sudo apt-get install -y aspnetcore-runtime-6.0
  build:
    commands:
      - ./publish.sh
artifacts:
  files:
    - "./deploy/DistanceTrackerFunction/DistanceTrackerFunction_$(cat version).zip"
    - "./deploy/DistanceTrackerFunctionSmoketest/DistanceTrackerFunctionSmoketest_$(cat version).zip"
